config/routes.rb
Rails.application.routes.draw do
  resources :stats
  resources :search

  root "stats#index"
  post 'auth/steam/callback' => 'auth#auth_callback'
  get 'logout' => 'auth#logout'
  get '*no_steam', to: 'errors#steam_down'
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  config.relative_url_root = ""

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  # auth callback POST comes from Steam so we can't attach CSRF token
  skip_before_filter :verify_authenticity_token, :only => :auth_callback

  def auth_callback
    auth = request.env['omniauth.auth']
    session[:user] = { :nickname => auth.info['nickname'],
                       :image => auth.info['image'],
                       :uid => auth.uid }
    
    redirect_to root_url
  end

  def logout
    session.delete(:user)
    redirect_to root_url
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def steam_down
    render 'errors/no_steam'
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @stats_count = Stat.distinct.count('steamid')
    if valid_search?
      redirect_to "/stats/#{search_params}"
    else
      render :template => 'search/index'
    end
  end

  private

  def valid_search?
    if params[:idSearch].nil? == false
      if is_i?(params[:idSearch])
        return true
      else
        return false
      end
    else
      return false
    end
  end

  def search_params
    params[:idSearch]
  end

  def is_i?(string)
    true if Float(string) rescue false
  end
end

app/controllers/stats_controller.rb
require 'playersum_schema'
require 'stats_schema'

class StatsController < ApplicationController
  include ActionView::Helpers::NumberHelper

  def index
    if user_is_logged_in?
      @steamid = session[:user]["uid"]
      @stats = getStats(@steamid)
    end
    @kd_ranks = Stat.order(kd: :desc)
    @wl_ranks = Stat.order(wl: :desc)
  end

  def show
    if params[:id].nil? == false
      @stats = getStats(params[:id])
      @playerSum = getPlayersum(params[:id])
      @pgStat = Stat.find_by(steamid: params[:id])
    end
  end

  private

  def getStats(steamid)
    begin
      userStats = StatsSchema.new(steamid)
      playerSum = PlayersumSchema.new(steamid)

      if userStats.stats_exist?
        if Stat.exists?(steamid: steamid)
          Stat.where(steamid: steamid).destroy_all
          @Stat = Stat.new(nickname: playerSum.nickname,
                           steamid: steamid,
                           total_kills: userStats.total_kills,
                           total_deaths: userStats.total_deaths,
                           wins: userStats.wins,
                           losses: userStats.losses,
                           matches_played: userStats.matches_played,
                           kd: kd_calc(userStats.total_kills, userStats.total_deaths),
                           wl: wl_calc(userStats.wins, userStats.losses))
          @Stat.save

          return userStats
        else
          @Stat = Stat.new(nickname: playerSum.nickname,
                           steamid: steamid,
                           total_kills: userStats.total_kills,
                           total_deaths: userStats.total_deaths,
                           wins: userStats.wins,
                           losses: userStats.losses,
                           matches_played: userStats.matches_played,
                           kd: kd_calc(userStats.total_kills, userStats.total_deaths),
                           wl: wl_calc(userStats.wins, userStats.losses))
          @Stat.save

          return userStats
        end
      else
        return "No stats available for this user.. :("
      end
    rescue SocketError => e
      render_steam_down

    rescue JSON::ParserError => e
      render_private_error
    end
  end

  def kd_calc(kills, deaths)
    result = (kills.to_f / deaths.to_f)
    number_with_precision(result, precision: 2, strip_insignificant_zeros: false).to_s
  end

  def wl_calc(wins, losses)
    result = (wins.to_f / losses.to_f)
    number_with_precision(result, precision: 2, strip_insignificant_zeros: false).to_s
  end

  def decimals(a)
    num = 0
    while(a != a.to_i)
        num += 1
        a *= 10
    end
    return num
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_is_logged_in?
   if session[:user].nil?
     return false
   else
     return true
   end
 end

 def getPlayersum(steamid)
   begin
     userSum = PlayersumSchema.new(steamid)
     return userSum
   rescue SocketError => e
     render_steam_down
   end
 end

 def render_steam_down
   respond_to do |format|
     format.html { render template: 'errors/no_steam', status: 404 }
     format.all { render nothing: true, status: 404 }
   end
 end

 def render_private_error
   respond_to do |format|
     format.html { render template: 'errors/private_profile', status: 400 }
     format.all { render nothing: true, status: 400 }
   end
 end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Kanit:600italic' rel='stylesheet' type='text/css'>

    <%= favicon_link_tag 'favicon.ico' %>

    <title><%= content_for?(:title) ? yield(:title) : "LiveStats: Quake Live Stat Hub" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="noselect">
      <div class="fixed">
        <nav class="top-bar" data-topbar role="navigation">
          <ul class="title-area">
            <li class="name">
              <h1 id="website-header"><a id="home-compass" href="/"><strong style="color:#811B1F">Live</strong><strong>Stats</strong></a></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
          </ul>

          <section class="top-bar-section">
            <!-- Right Nav Section -->
            <ul class="right">
              <li class="has-dropdown">
              <% if session.key? :user %>
                <li class="divider"></li>
                <li class="text-center"><a href="/stats/<%= session[:user]["uid"] %>" id="profile-link"><%= session[:user]["nickname"] %><%= image_tag session[:user]["image"], class: 'avatar' %></a></li>
                <li class="divider"></li>
                <li class="text-center"><a href="/logout" id="logout-link">Logout</a></li>
                <li class="divider"></li>
              <% else %>
                <li class="divider"></li>
                <li class="text-center"><%= link_to image_tag("http://cdn.steamcommunity.com/public/images/signinthroughsteam/sits_small.png"), '/auth/steam' %></li>
              <% end %>
            </ul>

            <ul class="left">
              <li id="search-field">
                <div class="row">
                  <div class="large-12 columns">
                    <%= form_tag search_index_path, method: :get do %>
                    <div class="row collapse">
                      <div class="small-10 columns">
                        <%= text_field_tag :idSearch, nil, placeholder: "Enter a SteamID", maxlength: 17 %>
                      </div>
                      <div class="small-2 columns">
                        <%= submit_tag "Get Stats", class: "button postfix", id: "top-bar-search-button" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </nav>
        </div>
        </br></br>
        <%= yield %>
        </br></br></br>
    </div>
    <%= javascript_include_tag "application" %>
  </body>

  <footer style="position:fixed;bottom:0;left:0;right:0;height:30px;">
    <div class="text-center" id="footer-bg">
      <div class="inline">
        <a href="http://steampowered.com" id="steampowered">Powered by Steam.</a>
      </div>
      <div class="inline">
        <p id="credit">Created by <a href="https://steamcommunity.com/id/cantstoptheb0p" style="color: #cccccc">b0p.</a></p>
      </div>
    </div>
  </footer>
</html>

app/views/search/index.html.erb
<div class="row">
  <div class="small-12 medium-6 small-centered medium-centered columns">
    <div class="text-center" id="search-page-counter-container">
      <strong><span id="search-page-counter" data-count="<%=@stats_count%>">0</span></strong>
      <br>
      <span id="search-page-counter-text"> unique profiles recorded.</span>
    </div>
    <div class="text-center" id="search-bar-container">
      <%= form_tag search_index_path, method: :get do %>
        <%= text_field_tag :idSearch, nil, placeholder: "SteamID goes here!", maxlength: 17 %>
        <%= submit_tag "Get Stats", class: "button", id: "search-page-search-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/stats/index.html.erb
<div class="row">
  <div class="small-12 medium-6 columns">
    <div id="kd-leaderboard-header-box">
      <h3 class="text-center" id="kd-leaderboard-header">K/D Leaderboard</h3>
    </div>
    <div class="" id="kd-leaderboard-box">
      <div id="kd-leaderboard-list-container">
        <ul class="" id="kd-leaderboard-list">
          <% @kd_ranks.each do |player| %>
            <a href="/stats/<%= player.steamid %>">
              <li>
                <img src="<%= getPlayersum(player.steamid).avatar_medium %>" class="leaderboard-image" width="50" height="50" />
                <h3><%= player.nickname %></h3>
                <div class="leaderboard-list-item-lower">
                  <h4>K/D: <strong><%= player.kd %></strong><h4>
                  <h6>Steam ID: <%= player.steamid %><h6>
                </div>
              </li>
            </a>
          <%end%>
        </ul>
      </div>
    </div>
    </br>
  </div>

  <div class="small-12 medium-6 columns">
    <div id="wl-leaderboard-header-box">
      <h3 class="text-center" id="wl-leaderboard-header">W/L Leaderboard</h3>
    </div>
    <div class="" id="wl-leaderboard-box">
      <div id="wl-leaderboard-list-container">
        <ul class="" id="wl-leaderboard-list">
          <% @wl_ranks.each do |player| %>
            <a href="/stats/<%= player.steamid %>">
              <li>
                <img src="<%= getPlayersum(player.steamid).avatar_medium %>" class="leaderboard-image" width="50" height="50" />
                <h3><%= player.nickname %></h3>
                <div class="leaderboard-list-item-lower">
                  <h4>W/L: <strong><%= player.wl %></strong><h4>
                  <h6>Steam ID: <%= player.steamid %><h6>
                </div>
              </li>
            </a>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
</div>